# Generated by Django 4.2.1 on 2023-05-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pic',
            field=models.FileField(default='prof.jpg', upload_to='profile_pics'),
        ),
    ]
